### PR TITLE
example of how to load data from test data in microservices github

### PR DESCRIPTION
**Pull request by adf-ncgr**
hopefully non-controversial

### CODE REVIEW

**Comment by alancleary** [comment]
I have a couple thoughts on this:

1. The microservices that use the Redis database will not run if the database doesn't have any data in it because technically a compatible version of the GCV schema hasn't been loaded, so it probably makes sense to actually load the example data this PR describes and add the generated `dump.rdb` file to the repo  under `data/redis/dump.rdb`. Then the services should actually run by default and admins can verify that everything is working correctly.
2. We should add a `data/docker-entrypoint-initdb.d/` directory to the repo and put a `test.sh` script in there that loads some data (it'll basically run the command this PR adds to the README). This directory will be mounted as a volume for the `redis_loader` service in `compose.yml` so users will more easily be able to hit the ground running with their own loading scripts, e.g. #6.

Both these changes will require further documentation in the README. What do you think @adf-ncgr? Is it worth including these changes in this PR? If yes, I can push some commits that do all this since I'm basically describing what I've already done while looking into #6.

**Comment by adf-ncgr** [comment]
I'm ambivalent- it seems like having the would be admin actually run through the steps they'll need to perform in order to get their own data in is healthy, rather than making it all automagical. But I think I at least seem some of the point to what you're suggesting (ie to get a "toy GCV" up and running with minimal effort). Anyway, I have no objection to your making additional changes if you want to, I just wanted to get something into place ASAP for @CFGrote to be able to refer to...

**Comment by alancleary** [comment]
OK. I'm well on my way to having thought (2) implemented and documented so let's move ahead with just that for now. Should have the commits pushed soon.

**Comment by alancleary** [comment]
I've pushed a commit that automatically mounts the `data/docker-entrypoint-initdb.d/` directory so admins can easily use their own scripts and a commit that updates the data loading documentation in the README. Let me know if you think anything else needs to be changed, otherwise feel free to merge!

**Comment by adf-ncgr** [comment]
looks good to me

**Comment by CFGrote** [comment]
I'm probably missing something obvious again, but the instructions in the updated README don't work for me:

Starting from a clean state (I removed killed and removed all containers/images after updating this repo and all submodules):

```
▶ docker-compose -f compose.yml -f compose.prod.yml kill  
Killing gcv_search_1        ... done
Killing gcv_redis_1         ... done
Killing gcv_envoy_1         ... done
Killing gcv_gcv_1           ... done
Killing gcv_reverse-proxy_1 ... done

▶ docker-compose -f compose.yml -f compose.prod.yml rm  
Going to remove gcv_redis_loader_run_dba435972559, gcv_redis_loader_run_20ac1f46f0d8, gcv_redis_loader_run_4dcc6798ffa1, gcv_search_1, gcv_redis_1, gcv_envoy_1, gcv_gcv_1, gcv_reverse-proxy_1
Are you sure? [yN] y
Removing gcv_redis_loader_run_dba435972559 ... done
Removing gcv_redis_loader_run_20ac1f46f0d8 ... done
Removing gcv_redis_loader_run_4dcc6798ffa1 ... done
Removing gcv_search_1                      ... done
Removing gcv_redis_1                       ... done
Removing gcv_envoy_1                       ... done
Removing gcv_gcv_1                         ... done
Removing gcv_reverse-proxy_1               ... done

▶ docker-compose -f compose.yml -f compose.prod.yml images
Container   Repository   Tag   Image Id   Size
----------------------------------------------
```

and then, following instructions:

```
docker-compose -f compose.yml -f compose.prod.yml run redis_loader gff --genus Glycine --species max --strain Wm82 --chromosome-gff https://github.com/legumeinfo/microservices/raw/main/tests/data/genome.gff3.gz --gene-gff https://github.com/legumeinfo/microservices/raw/main/tests/data/genes.gff3.gz --gfa https://github.com/legumeinfo/microservices/raw/main/tests/data/gfa.tsv.gz
```
produces 
```
Creating gcv_redis_loader_run ... done
usage: redis_loader [-h] [--version] [--redis-db REDIS_DB] [--redis-password REDIS_PASSWORD] [--redis-host REDIS_HOST]
                    [--redis-port REDIS_PORT] [--chunk-size CHUNK_SIZE] [--no-save] [--load-type {new,reload,append}]
                    [--sequence-types {chromosome,supercontig,chloroplast,mitochondrion} [{chromosome,supercontig,chloroplast,mitochondrion} ...]]
                    {chado,gff} ...
redis_loader: error: the following arguments are required: command
ERROR: 2
```
Same if I run redis_loader with no arguments.

**Comment by adf-ncgr** [comment]
no, you're right, the updated instructions are missing an argument (--load_type), it should be:
```
docker-compose -f compose.yml -f compose.prod.yml run redis_loader --load-type reload gff --genus Glycine --species max --strain Wm82 --chromosome-gff https://github.com/legumeinfo/microservices/raw/main/tests/data/genome.gff3.gz --gene-gff https://github.com/legumeinfo/microservices/raw/main/tests/data/genes.gff3.gz --gfa https://github.com/legumeinfo/microservices/raw/main/tests/data/gfa.tsv.gz
```
I have to admit that I think the cli for the loader could be more straightforward! But I'll update the README, let me know if that doesn't solve it for you.

**Comment by adf-ncgr** [comment]
Oh, OK - but I thought you couldn't actually use "append" the first time you run the loader when the db has no schema in place? Or maybe I've just fallen into bad habits on how I use it.

**Comment by alancleary** [comment]
`append` (and `reload`) works just fine when there's no database. It just tells the loader what to do if there's already a database.

**Comment by adf-ncgr** [comment]
OK, thanks; I guess I must have confused myself on that behavior at some point and never looked back.

**Pull request merged**
